name = "RegionalGrasslandSim"
uuid = "45e22d02-e628-441d-a1c7-54dcb4b48aca"
authors = ["Felix Nößler"]
version = "0.1.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
